from django.urls import path
from .views import (
    login_view,
    dashboard,
    empleados_list,
    empleado_create,
    empleado_edit,
    empleado_delete,
    seguridad,
    roles_list,
    rol_create,
    rol_edit,
    rol_delete,
    perfiles_list,
    perfil_create,
    perfil_edit,
    perfil_delete,
    rutas_list,
    ruta_create,
    ruta_edit,
    ruta_delete,
    permisos_list,
    permiso_create,
    permiso_edit,
    permiso_delete,
    logout_view,
    # Clientes
    clientes_list,
    cliente_create,
    cliente_edit,
    cliente_delete,
    # Tipos de Producto
    tipos_producto_list,
    tipo_producto_create,
    tipo_producto_edit,
    tipo_producto_delete,
    # Productos
    productos_list,
    producto_create,
    producto_edit,
    producto_delete,
    # Marcas
    marcas_list,
    marca_create,
    marca_edit,
    marca_delete,
    # Métodos de Pago
    metodos_pago_list,
    metodo_pago_create,
    metodo_pago_edit,
    metodo_pago_delete,
    # Tipos de Servicio
    tipos_servicio_list,
    tipo_servicio_create,
    tipo_servicio_edit,
    tipo_servicio_delete,
    # Estados de Servicio
    estados_servicio_list,
    estado_servicio_create,
    estado_servicio_edit,
    estado_servicio_delete,
)

urlpatterns = [
    path('login/', login_view, name='login'),
    path('dashboard/', dashboard, name='dashboard'),
    path('logout/', logout_view, name='logout'),
    path('empleados/', empleados_list, name='empleados_list'),
    path('empleados/create/', empleado_create, name='empleado_create'),
    path('empleados/<int:pk>/edit/', empleado_edit, name='empleado_edit'),
    path('empleados/<int:pk>/delete/', empleado_delete, name='empleado_delete'),
    path('seguridad/', seguridad, name='seguridad'),
    path('seguridad/roles/', roles_list, name='roles_list'),
    path('seguridad/roles/create/', rol_create, name='rol_create'),
    path('seguridad/roles/<int:pk>/edit/', rol_edit, name='rol_edit'),
    path('seguridad/roles/<int:pk>/delete/', rol_delete, name='rol_delete'),
    path('seguridad/perfiles/', perfiles_list, name='perfiles_list'),
    path('seguridad/perfiles/create/', perfil_create, name='perfil_create'),
    path('seguridad/perfiles/<int:pk>/edit/', perfil_edit, name='perfil_edit'),
    path('seguridad/perfiles/<int:pk>/delete/', perfil_delete, name='perfil_delete'),
    path('seguridad/rutas/', rutas_list, name='rutas_list'),
    path('seguridad/rutas/create/', ruta_create, name='ruta_create'),
    path('seguridad/rutas/<int:pk>/edit/', ruta_edit, name='ruta_edit'),
    path('seguridad/rutas/<int:pk>/delete/', ruta_delete, name='ruta_delete'),
    path('seguridad/permisos/', permisos_list, name='permisos_list'),
    path('seguridad/permisos/create/', permiso_create, name='permiso_create'),
    path('seguridad/permisos/<int:perfil_id>/<int:ruta_id>/edit/', permiso_edit, name='permiso_edit'),
    path('seguridad/permisos/<int:perfil_id>/<int:ruta_id>/delete/', permiso_delete, name='permiso_delete'),
    # Clientes
    path('clientes/', clientes_list, name='clientes_list'),
    path('clientes/create/', cliente_create, name='cliente_create'),
    path('clientes/<int:pk>/edit/', cliente_edit, name='cliente_edit'),
    path('clientes/<int:pk>/delete/', cliente_delete, name='cliente_delete'),
    # Tipos de Producto
    path('tipos-productos/', tipos_producto_list, name='tipos_producto_list'),
    path('tipos-productos/create/', tipo_producto_create, name='tipo_producto_create'),
    path('tipos-productos/<int:pk>/edit/', tipo_producto_edit, name='tipo_producto_edit'),
    path('tipos-productos/<int:pk>/delete/', tipo_producto_delete, name='tipo_producto_delete'),
    # Productos
    path('productos/', productos_list, name='productos_list'),
    path('productos/create/', producto_create, name='producto_create'),
    path('productos/<int:pk>/edit/', producto_edit, name='producto_edit'),
    path('productos/<int:pk>/delete/', producto_delete, name='producto_delete'),
    # Marcas
    path('marcas/', marcas_list, name='marcas_list'),
    path('marcas/create/', marca_create, name='marca_create'),
    path('marcas/<int:pk>/edit/', marca_edit, name='marca_edit'),
    path('marcas/<int:pk>/delete/', marca_delete, name='marca_delete'),
    # Métodos de Pago
    path('metodos-pago/', metodos_pago_list, name='metodos_pago_list'),
    path('metodos-pago/create/', metodo_pago_create, name='metodo_pago_create'),
    path('metodos-pago/<int:pk>/edit/', metodo_pago_edit, name='metodo_pago_edit'),
    path('metodos-pago/<int:pk>/delete/', metodo_pago_delete, name='metodo_pago_delete'),
    # Tipos de Servicio
    path('tipos-servicio/', tipos_servicio_list, name='tipos_servicio_list'),
    path('tipos-servicio/create/', tipo_servicio_create, name='tipo_servicio_create'),
    path('tipos-servicio/<int:pk>/edit/', tipo_servicio_edit, name='tipo_servicio_edit'),
    path('tipos-servicio/<int:pk>/delete/', tipo_servicio_delete, name='tipo_servicio_delete'),
    # Estados de Servicio
    path('estados-servicio/', estados_servicio_list, name='estados_servicio_list'),
    path('estados-servicio/create/', estado_servicio_create, name='estado_servicio_create'),
    path('estados-servicio/<int:pk>/edit/', estado_servicio_edit, name='estado_servicio_edit'),
    path('estados-servicio/<int:pk>/delete/', estado_servicio_delete, name='estado_servicio_delete'),
]
